#corpusDir: 'corpus'
#initialize: contracts/crytic/init.json
#testMode: benchmark
#testMode: optimization
#testMode: assertion
psender: "0x40000"
deployer: "0x40000"
#sender: ["0x40000", "0x50000", "0x50001", "0x50002"]
sender: ["0x40000"]
testLimit: 50000
shrinkLimit: 5000

cryticArgs: ["--solc-remaps", "@openzeppelin=node_modules/@openzeppelin @chainlink=node_modules/@chainlink", "--solc-args", "optimize optimize-runs=800 metadata-hash=none"]
#cryticArgs: ["--compile-force-framework", "hardhat"]
